name: 'Execute Powershell'

on:
  push:
    branches: [ action ]
    
jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Powershell - prepare.ps1
      run: .\prepare.ps1